#ifndef POLYCLINIC_SERVER_SERVER_CLIENTHANDLER_CONTROLLERS_CLIENTHANDLERCONTROLLER_HPP
#define POLYCLINIC_SERVER_SERVER_CLIENTHANDLER_CONTROLLERS_CLIENTHANDLERCONTROLLER_HPP

namespace server::client_handler::controllers {

class ClientHandlerController {

};

}   // !server::client_handler::controllers;

#endif  // !POLYCLINIC_SERVER_SERVER_CLIENTHANDLER_CONTROLLERS_CLIENTHANDLERCONTROLLER_HPP;